In [1]:
# Importing Libraries
import pandas as pd
import selenium
import time

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handles
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait

## 1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
* A) Rank
* B) Name
* C) Artist
* D) Upload date
* E) Views

In [2]:
# Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Getting the required url
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

time.sleep(2)

# scraping names of the video
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException: # handling no such element exception
    name.append('No details available')
    
time.sleep(2)   

#scraping rank of the video
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException: # handling no such element exception
    rank.append('No details available')

time.sleep(2)

#scraping Artist of the video
artist=[]
try:
    artists=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:  # handling no such element exception
    artist.append('No details available')
time.sleep(2)  

#scraping views of the video
views=[]
try:
    views_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException: # handling no such element exception
    views.append('No details available')
    
time.sleep(2) 

#scraping upload_date of the video
upload_date=[]
try:
    upload_date_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
except NoSuchElementException: # handling no such element exception
    upload_date.append('No details available')
    time.sleep(2) 
    
# Preparing dataframe
df = pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Uploader/artist":artist,
                "Date of upload":upload_date,
                "Views(in billion)":views})
df

,Rank,Name,Uploader/artist,Date of upload,Views(in billion)
0,1.,"""Baby Shark Dance""[23]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.44
1,2.,"""Despacito""[25]",Luis Fonsi,"January 12, 2017",7.57
2,3.,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016",5.77
3,4.,"""Shape of You""[27]",Ed Sheeran,"January 30, 2017",5.48
4,5.,"""See You Again""[28]",Wiz Khalifa,"April 6, 2015",5.28
5,6.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.55
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.52
7,8.,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"January 31, 2012",4.46
8,9.,"""Uptown Funk""[34]",Mark Ronson,"November 19, 2014",4.32
9,10.,"""Phonics Song with Two Words""[35]",ChuChu TV,"March 6, 2014",4.22
10,11.,"""Gangnam Style""[36]",Psy,"July 15, 2012",4.21
11,12.,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.63
12,13.,"""Sugar""[39]",Maroon 5,"January 14, 2015",3.56
13,14.,"""Sorry""[40]",Justin Bieber,"October 22, 2015",3.47
14,15.,"""Roar""[41]",Katy Perry,"September 5, 2013",3.44
15,16.,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",3.41
16,17.,"""Thinking Out Loud""[43]",Ed Sheeran,"October 7, 2014",3.34
17,18.,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.29
18,19.,"""Dark Horse""[45]",Katy Perry,"February 20, 2014",3.15
19,20.,"""Faded""[46]",Alan Walker,"December 3, 2015",3.15
20,21.,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.14
21,22.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.10
22,23.,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.10
23,24.,"""Shake It Off""[50]",Taylor Swift,"August 18, 2014",3.10
24,25.,"""Let Her Go""[51]",Passenger,"July 25, 2012",3.09
25,26.,"""Axel F""[52]",Crazy Frog,"June 16, 2009",3.03
26,27.,"""Mi Gente""[53]",J Balvin,"June 29, 2017",2.99
27,28.,"""Perfect""[54]",Ed Sheeran,"November 9, 2017",2.97
28,29.,"""Waka Waka (This Time for Africa)""[55]",Shakira,"June 4, 2010",2.96
29,30.,"""Hello""[56]",Adele,"October 22, 2015",2.89

## 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
* A) Match title (I.e. 1st ODI)
* B) Series
* C) Place
* D) Date
* E) Time

In [23]:
url = 'https://www.bcci.tv/' #getting the required url
driver.get(url)

time.sleep(2) #wait for 2 m.s.

fixtures=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover'][1]/div/ul/li[1]/a") #Locating to International Fixtures
driver.get(fixtures.get_attribute('href')) #Opening International Fixtuers page
time.sleep(2) #wait for 2 m.s.

Match_title = []
Series = []
Place = []
Date = []
Time = []

title=driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']") #Title of the Seriers
for i in title:
    Series.append(i.text)

    
name=driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']") #Match Title
for i in name:
    Match_title.append(i.text)

    
loc=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span") #Location
for i in loc:
    Place.append(i.text)
    dt1=driver.find_elements_by_xpath("//div[@class='fixture__full-date']/span") #Day
dt2=driver.find_elements_by_xpath("//div[@class='fixture__date-details']/span[1]") #Month
dat = len(dt1)
for i in range(0,dat):
    Date.append(dt1[i].text+" "+dt2[i].text) #adding Day and Month to form Date

    
tim=driver.find_elements_by_xpath("//div[@class='fixture__date-details']/span[2]") #Time
for i in tim:
    Time.append(i.text)
    
Fixtures=pd.DataFrame({}) #DataFrame
Fixtures['Match title'] = Match_title
Fixtures['Series'] = Series
Fixtures['Place'] = Place
Fixtures['Date'] = Date
Fixtures['Time'] = Time
Fixtures

,Match title,Series,Place,Date,Time
0,Match 16,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",24 OCTOBER,19:30 IST
1,Match 28,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",31 OCTOBER,19:30 IST
2,Match 33,2021 ICC MEN'S T20 WORLD CUP,"Zayed Cricket Stadium, Abu Dhabi",03 NOVEMBER,19:30 IST
3,Match 37,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",05 NOVEMBER,19:30 IST
4,Match 42,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",08 NOVEMBER,19:30 IST
5,1st T20I,INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",17 NOVEMBER,19:00 IST
6,2nd T20I,INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",19 NOVEMBER,19:00 IST
7,3rd T20I,INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",21 NOVEMBER,19:00 IST
8,1st Test,INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",25 NOVEMBER,09:30 IST
9,2nd Test,INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",03 DECEMBER,09:30 IST
10,1st Test,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",17 DECEMBER,13:30 IST
11,2nd Test,SOUTH AFRICA V INDIA 2021/2022,"Supersport Park, Centurion",26 DECEMBER,13:30 IST
12,3rd Test,SOUTH AFRICA V INDIA 2021/2022,"New Wanderers Stadium, Johannesburg",03 JANUARY,13:30 IST
13,1st ODI,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",11 JANUARY,14:00 IST
14,2nd ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",14 JANUARY,14:00 IST
15,3rd ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",16 JANUARY,14:00 IST
16,1st T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",19 JANUARY,19:30 IST
17,2nd T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",21 JANUARY,19:30 IST
18,3rd T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",23 JANUARY,19:30 IST
19,4th T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",26 JANUARY,19:30 IST

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
* A) Name
* B) Description
* Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [12]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the guru99.com
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)


#clicking on selenium option under testing menu open its tutorial
selenium_link=driver.find_element_by_xpath("//li[@id='menu-item-4622']/a")
try:
    selenium_link.click()
except:          #handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))
time.sleep(2)

#clicking on Selenium Exception Handling (Common Exceptions List) under Advance Webdriver Stuff!
exception_handle_link=driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handle_link.click()
except ElementNotInteractableException:      #handling element not clickable exception
    driver.get(exception_handle_link.get_attribute('href'))              
time.sleep(2)    
    
#scraping exceptions names
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names[1:]:
        name.append(i.text)
except NoSuchElementException:               #handling no such element exception
    name.append('No details available')
time.sleep(2)   

#scraping exceptions description
desc=[]
try:
    desc_list=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_list[1:]:
        desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    desc.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Exception_name":name,
                "Description":desc})
df

,Exception_name,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
* A) Rank
* B) State
* C) GSDP at current price (19-20)
* D) GSDP at current price (18-19)
* E) Share(18-19)
* F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code

In [4]:
# Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

url = 'http://statisticstimes.com/' #getting the required url
driver.get(url)
time.sleep(2)

# Clicking on Economy button
driver.find_element_by_xpath("//div[@class='navbar']/div[2]/button").click()

# Clicking on India
driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]").click()
time.sleep(3)

# Clicking on GDP of Indian Economy
GDP = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(3)

# Creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

# Scraping Rank
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# Scraping State
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# Scraping GSDP at current price (19-20)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
    # Scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# Scraping Share (18-19)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# Scraping GDP $ billion
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")
    
# Creating DataFrame from the scraped data
GDP = pd.DataFrame({})
GDP['Rank'] = Rank
GDP['State'] = State
GDP['GSDP at current price (19-20)'] = GSDP1
GDP['GSDP at current price (18-19)'] = GSDP2
GDP['Share(18-19)'] = Share
GDP[' GDP($ billion)'] = GDP_billion
GDP

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/ 
You have to find the following details: 
* A) Repository title 
* B) Repository description 
* C) Contributors count 
* D) Language used 
* Note: - From the home page you have to click on the trending option from Explore menu through code.

In [77]:
# Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

url = 'https://github.com/' #getting the required url
driver.get(url)

time.sleep(2)

# Getting explore button and clicking on it
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()

#Selecting trending option
trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

#Creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

#Fetching urls for each repository
repository = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

    
# Scraping Repository Title data
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

    
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(3)
    
    
    # Scraping Repository Description data
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        # Scraping Contributors Count data
    try:
        contributor = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
            
    # Scraping Languages used data
    try:
        for i in driver.find_elements_by_xpath("//span[@class='color-text-primary text-bold mr-1']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')
        
#creating dataframe
Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,peng-zhihui / Dummy-Robot,我的超迷你机械臂机器人项目。,-,"[Python, Jinja, Shell, Other, Java, JavaScript..."
1,trailofbits / algo,Set up a personal VPN in the cloud,156,"[Python, Jinja, Shell, Other, Java, JavaScript..."
2,Snailclimb / JavaGuide,「Java学习+面试指南」一份涵盖大部分 Java 程序员所需要掌握的核心知识。准备 Jav...,261,"[Python, Jinja, Shell, Other, Java, JavaScript..."
3,louislam / uptime-kuma,A fancy self-hosted monitoring tool,60,"[Python, Jinja, Shell, Other, Java, JavaScript..."
4,vuejs / vue-next,"🖖 Vue.js is a progressive, incrementally-adopt...",280,"[Python, Jinja, Shell, Other, Java, JavaScript..."
5,babysor / MockingBird,🚀AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 s...,10,"[Python, Jinja, Shell, Other, Java, JavaScript..."
6,facebook / flipper,A desktop debugging platform for mobile develo...,219,"[Python, Jinja, Shell, Other, Java, JavaScript..."
7,fatedier / frp,A fast reverse proxy to help you expose a loca...,71,"[Python, Jinja, Shell, Other, Java, JavaScript..."
8,ossrs / srs,"SRS is a simple, high efficiency and realtime ...",64,"[Python, Jinja, Shell, Other, Java, JavaScript..."
9,vinta / awesome-python,"A curated list of awesome Python frameworks, l...",392,"[Python, Jinja, Shell, Other, Java, JavaScript..."
10,yt-dlp / yt-dlp,A youtube-dl fork with additional features and...,854,"[Python, Jinja, Shell, Other, Java, JavaScript..."
11,ihciah / clean-dns-bpf,基于 Rust + eBPF 丢弃 GFW DNS 污染包,-,"[Python, Jinja, Shell, Other, Java, JavaScript..."
12,sdras / awesome-actions,A curated list of awesome actions to use on Gi...,280,"[Python, Jinja, Shell, Other, Java, JavaScript..."
13,Hack-with-Github / Awesome-Hacking,A collection of various awesome lists for hack...,21,"[Python, Jinja, Shell, Other, Java, JavaScript..."
14,anncwb / vue-vben-admin,"A modern vue admin. It is based on Vue3, vite ...",72,"[Python, Jinja, Shell, Other, Java, JavaScript..."
15,Python-World / Python_and_the_Web,"Build Bots, Scrape a website or use an API to ...",102,"[Python, Jinja, Shell, Other, Java, JavaScript..."
16,wimpysworld / quickemu,"Quickly create and run optimised Windows, macO...",16,"[Python, Jinja, Shell, Other, Java, JavaScript..."
17,mattiasgustavsson / dos-like,"Engine for making things with a MS-DOS feel, b...",3,"[Python, Jinja, Shell, Other, Java, JavaScript..."
18,apache / rocketmq,Mirror of Apache RocketMQ,280,"[Python, Jinja, Shell, Other, Java, JavaScript..."
19,donet5 / WebFirst,.NET CORE 代码生成器 ，Web中使用CodeFirst模式， 实体生成器，UI代码...,-,"[Python, Jinja, Shell, Other, Java, JavaScript..."
20,raywenderlich / flta-materials,The projects and the materials that accompany ...,8,"[Python, Jinja, Shell, Other, Java, JavaScript..."
21,herosi / CTO,Call Tree Overviewer,-,"[Python, Jinja, Shell, Other, Java, JavaScript..."
22,alibaba / Sentinel,A powerful flow control component enabling rel...,152,"[Python, Jinja, Shell, Other, Java, JavaScript..."
23,alibaba / spring-cloud-alibaba,Spring Cloud Alibaba provides a one-stop solut...,114,"[Python, Jinja, Shell, Other, Java, JavaScript..."
24,vuejs / vue,"🖖 Vue.js is a progressive, incrementally-adopt...",401,"[Python, Jinja, Shell, Other, Java, JavaScript..."

# 6. Scrape the details of top 100 songs on billiboard.com.
Url = https://www.billboard.com/ 
You have to find the following details: 
* A) Song name 
* B) Artist name 
* C) Last week rank 
* D) Peak rank 
* E) Weeks on board
* Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [14]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)


#clicking the hot 100 songs link
charts=driver.find_element_by_xpath("//ul[@class='header__subnav__list display--flex flex--left-center flex-md--center-center']//li[3]//a")
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)


#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)    


#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('No details available')
time.sleep(2)
    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(2)

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(2)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,My Universe,Coldplay x BTS,-,1,1
1,Stay,The Kid LAROI & Justin Bieber,1,1,12
2,Industry Baby,Lil Nas X & Jack Harlow,2,2,10
3,Way 2 Sexy,Drake Featuring Future & Young Thug,3,1,4
4,Fancy Like,Walker Hayes,5,5,15
...,...,...,...,...,...
95,Pipe Down,Drake,68,14,4
96,Papi's Home,Drake,66,8,4
97,Chosen,Blxst & Tyga Featuring Ty Dolla $ign,-,98,1
98,Toxic Punk,YoungBoy Never Broke Again,-,99,1
99,Moon,Kanye West,76,17,5

# 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
* A) Name
* B) Designation
* C) Company
* D) Skills they hire for
* E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [16]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the naukri.com
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)
#Fetching urls to navigate recruiter page
recruiter = driver.find_element_by_xpath("//a[@title='Search Recruiters']")
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

# Fetching search button, sending keys and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()     
time.sleep(3)
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)


#Scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
time.sleep(3)

#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)
time.sleep(3)
    
#scraping data of Skills 
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
    time.sleep(3)
    #Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name[:50]
Naukri['Designation'] = Designation[:50]
Naukri['Company'] = Company[:50]
Naukri['Skills'] = Skills[:50]
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Company Recruiter
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Hyderabad / Secunderabad
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",MARSIAN Technologies LLP
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Company HR
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Pune
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Anik Agrawal
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehousing, ET...",Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Narasimha
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Company Recruiter
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Hyderabad / Secunderabad
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",subhas patel
16,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Founder CEO
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",UK - (london)
18,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Abhishek - Only Analytics Hiring - India and
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Recruitment Lead Consultant
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Vadodara / Baroda
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Institute for Financial Management and Resear
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Programme Manager
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Chennai
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Balu Ramesh
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",HR Administrator
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Trivandrum
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Asif Lucknowi
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Director
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Indore
30,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",InstaFinancials
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Human Resource
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Bengaluru / Bangalore
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Priyanka Akiri
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,HR Manager
35,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Hyderabad
36,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Kalpana Dumpala
37,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Executive Hiring
38,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Hyderabad / Secunderabad
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Mubarak
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Company HR
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Kushal Rastogi
43,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Company HR
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Mumbai
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Ruchi Dhote
46,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Senior Executive Talent Acquisition
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Pune
48,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mahesh Babu Channa
49,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",HR Team Lead

# 8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
* A) Book name
* B) Author name
* C) Volumes sold
* D) Publisher
* E) Genre

In [41]:
# Activating web driver
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Getting required url
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver.get(url)
time.sleep(2)

# Creating empty lists
Book_name =[]
Author_name = []
Volumes_sold= []
Publisher = []
Genre = []

# Scraping book name details
for i in driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]"):
    Book_name.append(i.text)

# Scraping author name details
for i in driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]"):
    Author_name.append(i.text)

# Scraping Volumes sold details
for i in driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]"):
    Volumes_sold.append(i.text)

# Scraping Publisher details
for i in driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]"):
    Publisher.append(i.text)

# Scraping Genre details
for i in driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]"):
    Genre.append(i.text)

# Creating dataframe to store the fethched data
Novels = pd.DataFrame({'Book_name':Book_name,'Author_name':Author_name,'Volumes_sold':Volumes_sold,'Publisher':Publisher,'Genre':Genre})
Novels

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.
 Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
* A) Name
* B) Year span
* C) Genre
* D) Run time
* E) Ratings
* F) Votes

In [39]:
# Activating the Chrome browser
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Getting required url
url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)

# Creating empty lists
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

# Scraping name of the movie
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

# Scrpaing Year span 
for i in driver.find_elements_by_xpath("//span[@class='lister-item-index unbold text-primary']"):
    Year_span.append(i.text)
    
# Scrpaing Genre 
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)
    
# Scrpaing Run_time 
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)
    
# Scrpaing Ratings 
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
    Ratings.append(i.text)
    
# Scrpaing Votes 
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)
    
print(len(Name),len(Year_span),len(Genre),len(Run_time),len(Ratings),len(Votes))

100 100 100 100 100 100

In [40]:
Tv_series = pd.DataFrame({'Name':Name,'Year_span':Year_span,'Genre':Genre,'Run_time':Run_time,'Ratings':Ratings,'Votes':Votes})
Tv_series

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,1.,"Action, Adventure, Drama",57 min,9.2,"1,882,009"
1,Stranger Things,2.,"Drama, Fantasy, Horror",51 min,8.7,"915,463"
2,The Walking Dead,3.,"Drama, Horror, Thriller",44 min,8.2,"903,977"
3,13 Reasons Why,4.,"Drama, Mystery, Thriller",60 min,7.5,"270,865"
4,The 100,5.,"Drama, Mystery, Sci-Fi",43 min,7.6,"231,253"
...,...,...,...,...,...,...
95,Reign,96.,"Drama, Fantasy",42 min,7.5,"45,882"
96,A Series of Unfortunate Events,97.,"Adventure, Comedy, Drama",50 min,7.8,"56,755"
97,Criminal Minds,98.,"Crime, Drama, Mystery",42 min,8.1,"177,243"
98,Scream: The TV Series,99.,"Comedy, Crime, Drama",45 min,7.1,"36,871"
99,The Haunting of Hill House,100.,"Drama, Horror, Mystery",572 min,8.6,"203,414"

# 10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
* A) Dataset name
* B) Data type
* C) Task
* D) Attribute type
* E) No of instances
* F) No of attribute
* G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [76]:
# Activating web Chrome browser
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Getting required url
url = "https://archive.ics.uci.edu/"
driver.get(url)

#Clicking on view all datasets link
datasets=driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b")
try:
    datasets.click()
except ElementNotInteractableException:
    driver.get(datasets.get_attribute('href'))

#Creating empty lists for storing the data
Name=[]
Type=[]
Task=[]
Attribute=[]
No_of_Instance=[]
No_of_Attribute=[]
Year=[]

#Scrapping the data having dataset name
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
    
#Scrapping the data having data type
try:
    types=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in types[1:]:
        Type.append(i.text)
except NoSuchElementException:
    Type.append('-')
    
#Scrapping the data having default task
try:
    task=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('-')
        
#Scrapping the data having attribute types
try:
    attribute=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:
     Attribute.append('-')
        
#Scrapping the data having no of instances
try:
    instance=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:
    No_of_Instance.append('-')
        
#Scrapping the data having no of attributes
try:
    attribute_no=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute_no[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('-')
        
#Scrapping the data having the year details
try:
    year=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('-')
    

#Creating the dataframe
df=pd.DataFrame({"Name":Name,"Data types":Type,"Default Task":Task,"Attribute types":Attribute, 
                 "No of instances":No_of_Instance,"No of atrributes":No_of_Attribute,"Year":Year})
df

,Name,Data types,Default Task,Attribute types,No of instances,No of atrributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021