10. Write a python program to scrape house details from https://www.nobroker.in/ for any location. It should include house title, location, area, emi and price

In [57]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [58]:
hse = requests.get('https://www.nobroker.in/property/sale/mumbai/Marine%20Drive?searchParam=W3sibGF0IjoxOC45NDE0NTkyLCJsb24iOjcyLjgyMzYyOTUsInBsYWNlSWQiOiJDaElKSFZfLTNPSFI1enNSYWU3em11RUEzQzAiLCJwbGFjZU5hbWUiOiJNYXJpbmUgRHJpdmUifV0=&radius=2.0')
hse

In [59]:
Soup = BeautifulSoup(hse.content)

In [60]:
name = Soup.find_all('a',class_='nb__3CnI6')
loc = Soup.find_all('div',class_='nb__2CMjv')
Emi = Soup.find_all('div',class_='font-semi-bold heading-6')
ar = Soup.find_all('div',class_='nb__3oNyC')
pr = Soup.find_all('div',class_='font-semi-bold heading-6')

In [61]:
Titles = []
Locations = []
EMI = []
Area = []
Price = []

In [73]:
for i in name:
    for j in i.find_all('span'):
        Titles.append(j.text)
for l in loc:
    Locations.append(l.text)
    
for e in Emi:
    EMI.append(e.text)
for a in ar:
    Area.append(a.text)
for p in pr:
    for q in p.find_all('span'):
        Price.append(q.text)

Extract Emi and Price data

In [74]:
emi = []
for i in range(1,len(EMI),3):
    emi.append(EMI[i])

In [75]:
price = []
for p in range(1,len(Price),2):
    price.append(Price[p])

In [65]:
emi

['₹2.84 Lacs/Month',
 '₹3.15 Lacs/Month',
 '₹5.53 Lacs/Month',
 '₹5.16 Lacs/Month',
 '₹3.01 Lacs/Month',
 '₹1.2 Lacs/Month',
 '₹4.18 Lacs/Month',
 '₹22,925/Month',
 '₹74,508/Month',
 '₹58,460/Month']

In [77]:
price[:10]

['₹4.95 Crores',
 '₹5.5 Crores',
 '₹9.65 Crores',
 '₹9 Crores',
 '₹5.25 Crores',
 '₹2.1 Crores',
 '₹7.3 Crores',
 '₹40 Lacs',
 '₹1.3 Crores',
 '₹1.02 Crores']

In [80]:
House = {'Title':Titles,'Location':Locations,'Area':Area, 'EMI estimated':emi,'Price':price[:10]}

df = pd.DataFrame.from_dict(House, orient='index')

df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Title,2 BHK Flat For Sale In Marine Drive,2 BHK Flat For Sale In Bharat Mahal In Marin...,3 BHK Flat For Sale In Shyam Sadan In Marine...,3 BHK Flat For Sale In Parijat In Churchgate,2 BHK Flat For Sale In Shalimar Building In ...,2 BHK Flat For Sale In Dhan Bhuvan No.1 In M...,2 BHK Flat For Sale In Krishna Mahal In Chur...,1 RK Flat For Sale In Marine Lines,2 BHK Flat For Sale In Kapadia House In Metr...,1 BHK Flat For Sale In Har Har Mahadev Socie...,...,2 BHK Flat For Sale In Marine Drive,2 BHK Flat For Sale In Bharat Mahal In Marin...,3 BHK Flat For Sale In Shyam Sadan In Marine...,3 BHK Flat For Sale In Parijat In Churchgate,2 BHK Flat For Sale In Shalimar Building In ...,2 BHK Flat For Sale In Dhan Bhuvan No.1 In M...,2 BHK Flat For Sale In Krishna Mahal In Chur...,1 RK Flat For Sale In Marine Lines,2 BHK Flat For Sale In Kapadia House In Metr...,1 BHK Flat For Sale In Har Har Mahadev Socie...
Location,"Standalone Building, Marine Lines Flyover, Chu...","F Rd, Marine Drive, Mumbai, Maharashtra 400002...","85, Marine Lines Flyover, Marine Lines, Mumbai...","Shamaldas Gandhi Rd, ,Near State Bank of India",RoC G Road Near Vaishali Saree Emporium,"5-21/22 , Dhan Bhuvan no.1 , Gazder street, c...","Vinoo Mankad Rd Churchgate Mumbai, Maharashtra","Standalone Building, Maharshi Karve Rd, near S...",behind Cawasaji Hall,"Standalone building, Near BMC C Ward, Chandan ...",...,None,None,None,None,None,None,None,None,None,None
Area,"1,200 sqft","1,000 sqft","1,680 sqft","1,400 sqft","1,302 sqft",580 sqft,"1,130 sqft",120 sqft,840 sqft,585 sqft,...,None,None,None,None,None,None,None,None,None,None
EMI estimated,₹2.84 Lacs/Month,₹3.15 Lacs/Month,₹5.53 Lacs/Month,₹5.16 Lacs/Month,₹3.01 Lacs/Month,₹1.2 Lacs/Month,₹4.18 Lacs/Month,"₹22,925/Month","₹74,508/Month","₹58,460/Month",...,₹2.84 Lacs/Month,₹3.15 Lacs/Month,₹5.53 Lacs/Month,₹5.16 Lacs/Month,₹3.01 Lacs/Month,₹1.2 Lacs/Month,₹4.18 Lacs/Month,"₹22,925/Month","₹74,508/Month","₹58,460/Month"
Price,₹4.95 Crores,₹5.5 Crores,₹9.65 Crores,₹9 Crores,₹5.25 Crores,₹2.1 Crores,₹7.3 Crores,₹40 Lacs,₹1.3 Crores,₹1.02 Crores,...,None,None,None,None,None,None,None,None,None,None