Q.9 Write a python program to scrape fresher job listings from ‘https://internshala.com/’. It should include job title, company name, CTC, and apply date.

In [24]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [25]:
intrn = requests.get('https://internshala.com/fresher-jobs')
intrn

In [26]:
Soup = BeautifulSoup(intrn.content, 'lxml')

In [27]:
jb = soup.find_all('div',class_='heading_4_5 profile')
intshp = soup.find_all('div',class_='internship_meta')

In [28]:
job = []
company = []
CTC_apply = []

In [29]:
for x in jb:
    for j in x.find_all('a'):
        job.append(j.text.strip().replace('\n',''))
for i in intshp:
    
    for c in i.find_all('a',class_='link_display_like_text'):
        company.append(c.text.strip().replace('\n',''))
    
    for t in i.find_all('div',class_='item_body'):
        CTC_apply.append(t.text.strip().replace('\n','').strip().replace('\n',''))

Separate CTC and Apply By Dates

In [30]:
CTC = []
Apply = []

In [31]:
for c in range (1,len(CTC_apply),3):
    CTC.append(CTC_apply[c])
    
for a in range(2,len(CTC_apply),3):
    Apply.append(CTC_apply[a])

In [32]:
Apply

["18 Sep' 21",
 "11 Sep' 21",
 "11 Sep' 21",
 "4 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "29 Sep' 21",
 "27 Sep' 21",
 "27 Sep' 21",
 "27 Sep' 21",
 "27 Sep' 21",
 "27 Sep' 21",
 "27 Sep' 21",
 "26 Sep' 21",
 "29 Sep' 21",
 "26 Sep' 21",
 "26 Sep' 21",
 "26 Sep' 21",
 "26 Sep' 21",
 "26 Sep' 21",
 "26 Sep' 21",
 "25 Sep' 21",
 "25 Sep' 21",
 "25 Sep' 21",
 "25 Sep' 21",
 "25 Sep' 21",
 "25 Sep' 21",
 "25 Sep' 21",
 "24 Sep' 21",
 "24 Sep' 21",
 "24 Sep' 21",
 "24 Sep' 21",
 "24 Sep' 21",
 "23 Sep' 21",
 "23 Sep' 21"]

In [33]:
Jobs = {'Title':job,'Company':company,'CTC(₹)':CTC, 'Apply By':Apply}
Jobs  = pd.DataFrame(Jobs)
Jobs

,Title,Company,CTC(₹),Apply By
0,OMNI SPORT LEADER,Decathlon Sport India Private Limited,3 - 4 LPA,18 Sep' 21
1,Executive/Senior Executive - Partnerships,Freecharge Payments Technology Private Limited,3 - 4.2 LPA,11 Sep' 21
2,Executive - Sales,Freecharge Payments Technology Private Limited,3 - 3.5 LPA,11 Sep' 21
3,Junior Operations Executive,Freecharge Payments Technology Private Limited,3 - 4 LPA,4 Sep' 21
4,Associate Web Developer,WebMOBI,3 LPA,29 Sep' 21
5,Engineering Admissions Writer,GREedge,5.2 LPA,29 Sep' 21
6,Assistant Manager - Product Development & Prog...,SUPROS,4.2 - 4.5 LPA,29 Sep' 21
7,Junior Full Stack Developer,Techdome Solutions Private Limited,3 - 6 LPA,29 Sep' 21
8,Strategy Analyst,RedCarpetUp,6 LPA,29 Sep' 21
9,Associate Recruiter,Talhive,3 - 5 LPA,29 Sep' 21
10,Laravel Developer,Brainbean Technolabs Private Limited,3 LPA,29 Sep' 21
11,PHP Developer,Krishworks,3 - 6 LPA,29 Sep' 21
12,Inside Sales Executive,Neo91 (DSBL Private Limited),3.5 LPA,27 Sep' 21
13,Sales Client Onboarding Executive,Intesome,3 - 4 LPA,27 Sep' 21
14,B2B Digital Sales Executive,Intesome,3 - 4 LPA,27 Sep' 21
15,Business Development Executive,AAPC India Private Limited,3 - 4.5 LPA,27 Sep' 21
16,Customer Service Executive,InfyBytes AI Labs Private Limited,3 - 4 LPA,27 Sep' 21
17,Business Development Associate,XOOG EDLEARN PRIVATE LIMITED,4.5 - 7 LPA,27 Sep' 21
18,Trainee Software Engineer,NuWare Systems,3 - 4 LPA,26 Sep' 21
19,Associate (Development),Pratham InfoTech Foundation,3 - 3.5 LPA,29 Sep' 21
20,Corporate Sales Associate,Best Roadways Limited,3 LPA,26 Sep' 21
21,Sales Executive,Hedge Homes,3 - 3.5 LPA,26 Sep' 21
22,Organizational Behavior Specialist,SysCloud Technologies Private Limited,4.5 - 6 LPA,26 Sep' 21
23,International Online Sales Executive,Intesome,3 - 4 LPA,26 Sep' 21
24,Digital Marketing Specialist,Ohana Academy,3 - 5 LPA,26 Sep' 21
25,Buddy Counselor (Study Abroad),UniAcco,3 - 5 LPA,26 Sep' 21
26,Student Success - Teacher,Code A Block (KEDTech LLC),4 - 7.2 LPA,25 Sep' 21
27,Supply Chain Executive,Serturner,3 LPA,25 Sep' 21
28,Game Developer,Cogent Web Services,3 LPA,25 Sep' 21
29,Associate - Digital Products,RocSearch,3.5 - 4 LPA,25 Sep' 21
30,Program Impact In-charge (Science And Mathemat...,Open Door Education,6 - 10 LPA,25 Sep' 21
31,Software Engineer Trainee,Markytics,3 - 4 LPA,25 Sep' 21
32,Sales Executive,1st In Class,3 - 3.2 LPA,25 Sep' 21
33,Digital Marketing Executive,TradeVinder,3 - 4 LPA,24 Sep' 21
34,Corporate Sales Manager,FinDestination,3 LPA,24 Sep' 21
35,Software Developer,Innovantes IT Solutions LLP,3 - 3.1 LPA,24 Sep' 21
36,Executive Assistant To Director,Best Roadways Limited,3 LPA,24 Sep' 21
37,C++ Embedded/Semiconductor Expert (SoC Modeling),Circuitsutra Technologies Private Limited,6 LPA,24 Sep' 21
38,Mobile App Developer,Cogent Web Services,3 LPA,23 Sep' 21
39,Software Developer,Swabhav Techlabs,3 - 3.5 LPA,23 Sep' 21